### ISSUE TITLE
When will @optimajet/workflow-designer-react support React v18?

### ISSUE THREAD

**Issue by briannoyes** [optimajet/workflow-designer-react-sample#2]
Many of the samples already have their dependencies set to React v18, but when you try to install packages with npm, the install fails because the designer library only supports React v17.0.2. When do you plan to update it to support v18?

**Comment by optimajet** [comment]
@briannoyes We plan to add support for React 18 in one of our upcoming releases.

**Comment by sergeythrees** [comment]
Hi, @briannoyes 
We have already added support React 18.
